# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-04 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satisdokumbilgi',
            name='sgketkinkod',
            field=models.TextField(blank=True, null=True),
        ),
    ]
