# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-05 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180405_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satisdokumbilgi',
            name='islem_tarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
